language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
sudo: false
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: kXVJJ91G/wsCz7aX4d8fb+5PbfuJz3d4J0Z/HDyTIu45BzY5vC/3OkqUfTXQEHnxT+xkBG3BjCEe6qq5KaAK+vRTpu1Y7uFaWnJ0QwTJ1EVpcM0uqoFi51gzDpetY/8LmA2V10t3085U0aX6gsp8gBLd+QCIcCAp9+Q/nKaPcoU=
  on:
    tags: true
    repo: flowbased/fbp-protocol-client
